apiVersion: v1
kind: Pod
metadata:
   name: pod-1
spec:
   initContainers:
   - name: kubernetes-db2
     image: hongreu999/db2
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: "5678"
     - name: MYSQL_DATABASE
       value: "travel_list"
   containers:
   - name: kubernetes-backend
     image: hongreu999/backend
     env:
     - name: DB_PORT
       value: "3306"
     - name: DB_HOST
       value: "localhost"
     - name: DB_NAME
       value: "travel_list"
     - name: DB_USERNAME
       value: "root"
     - name: DB_PASSWORD
       value: "5678"
     - name: DB_SCHEMA
       value: "public"
     - name: DDL_METHOD
       value: "update"